name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Adicione outras ações para construir,
          echo testar e implantar seu projeto.

  buscar_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Buscar Pull Requests com 'teste' no título
        id: find_pull_requests
        run: |
          pull_requests=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | \
            jq -r '.[] | select(.title | test("teste"; "i")) | .number')
          echo "::set-output name=pull_requests::$pull_requests"

      - name: Adicionar revisores aos Pull Requests
        if: steps.find_pull_requests.outputs.pull_requests != ''
        run: |
          for pr_number in ${{ steps.find_pull_requests.outputs.pull_requests }}; do
            echo "Adicionando revisores ao Pull Request #$pr_number"
            gh pr edit $pr_number --add-reviewer andressagomes 
          done